### ISSUE TITLE
Where did this go?

### ISSUE THREAD

**Issue by ciriousjoker** [PavieOlivier/g-drive-alternative#2]
I assume this project is dead? What was the purpose of it? Now that it's gone, I'm curious :D

**Comment by PavieOlivier** [comment]
hum... I never released it( which is strange cause I had it working hum...)
Firebase does not support index search and they were promoting Algolia at the time...
So I made a package with some tricks in it to reduce the calls to Firestore and get the data In an efficient way. However, my laptop got Stolen at the time so I lost lots of packages and side projects I was working on.

With that aside,

If you are looking for better solutions for searching
-  I would strongly recommend installing **[meilisearch](https://www.meilisearch.com/)**; it is open source and you can self-host it. Set it up on a server and synch your data to it. if you don't want to  pay now you can run it locally on your docker. If you want it online because you have a teammate somewhere else, run it via a GitPod

- Secondly, I would not recommend Firebase anymore to anyone... there are so many better solutions out there ( if you are willing to do some grinding ) that do not lock your data in and also do not cost you $ in the long run. 

 I would recommend you to have a look at [appwrite](https://appwrite.io/), it is a backend as a service that you can self-host on a VPS ( or locally on docker ) or you can use their cloud solution. At the moment I feel that It is way better than Firestore in terms of features and if you are worried about scaling I have a friend who made an entire website to explain how to scale appwrite to be able to handle load for different levels ( up to Facebook level scaling lol )

- For storage  like s3 use Wasabi, It will cost you less than AWS or Google Cloud and its fast and secure too

At last, 
If you have any questions or require any help someday in your code,  feel free to message me. Would be glad to help ya

**Comment by ciriousjoker** [comment]
Ah ok, interesting. For now, we're all in on Firestore, for our purposes it's perfect although it's a huge shift from regular databases. Also Algolia is free for our usage tier so we're using that. The latency is insane on this thing so we're happy atm. Perhaps in the future this might change

**Comment by PavieOlivier** [comment]
cool 😎
I will be closing this thread then :)
